# Generated by Django 5.2.4 on 2025-07-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
