# Generated by Django 5.2.4 on 2025-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toD', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
